#!/bin/bash

SECONDS=0
cd g2
echo ''
echo ''
echo ''
echo '---------------------------------------'
echo '- TESTING EXPLICIT GENUS 2 ARITHMETIC -'
echo '---------------------------------------'
echo ''
cd splitModel
echo ''
echo ''
echo ''
echo '-------------------------------------------------------------------------------'
echo '- TESTING EXPLICIT GENUS 2 BALANCED SPLIT MODEL ARITHMETIC (Positive Reduced) -'
echo '-------------------------------------------------------------------------------'
echo ''
echo ''
sleep 5
cd posReduced
echo '-------------------------------------------'
echo '  White Box Testing Over Arbitrary Fields  '
echo '-------------------------------------------'
echo ''
sleep 1
magma 'arb_splitG2_whiteBox_tester.mag'
echo ''
echo '----------------------------------------'
echo '  Random Testing Over Arbitrary Fields  '
echo '----------------------------------------'
echo ''
sleep 1
magma 'arb_splitG2_random.mag'
echo ''
echo '------------------------------------------'
echo '  Finished Testing Over Arbitrary Fields  '
echo '------------------------------------------'
echo ''
echo ''
sleep 3
echo '--------------------------------------------------'
echo '  White Box Testing Over Characteristic 2 Fields  '
echo '--------------------------------------------------'
echo ''
sleep 1
magma 'ch2_splitG2_whiteBox_tester.mag'
echo ''
echo '-----------------------------------------------'
echo '  Random Testing Over Characterisitc 2 Fields  '
echo '-----------------------------------------------'
echo ''
sleep 1
magma 'ch2_splitG2_random.mag'
echo ''
echo '-------------------------------------------------'
echo '  Finished Testing Over Characteristic 2 Fields  '
echo '-------------------------------------------------'
echo ''
echo ''
sleep 3
echo '----------------------------------------------------'
echo '  White Box Testing Over Characteristic !=2 Fields  '
echo '----------------------------------------------------'
echo ''
sleep 1
magma 'nch2_splitG2_whiteBox_tester.mag'
echo ''
echo '-------------------------------------------------'
echo '  Random Testing Over Characteristic !=2 Fields  '
echo '-------------------------------------------------'
echo ''
sleep 1
magma 'nch2_splitG2_random.mag'
echo ''
echo '---------------------------------------------------'
echo '  Finished Testing Over Characteristic !=2 Fields  '
echo '---------------------------------------------------'
echo ''
echo ''
sleep 3
echo ''
echo ''
echo ''
echo '-------------------------------------------------------------------------------'
echo '- TESTING EXPLICIT GENUS 2 BALANCED SPLIT MODEL ARITHMETIC (Negative Reduced) -'
echo '-------------------------------------------------------------------------------'
echo ''
echo ''
sleep 5
cd ../negReduced
echo '-------------------------------------------'
echo '  White Box Testing Over Arbitrary Fields  '
echo '-------------------------------------------'
echo ''
sleep 1
magma 'arb_splitG2_whiteBox_tester.mag'
echo ''
echo '----------------------------------------'
echo '  Random Testing Over Arbitrary Fields  '
echo '----------------------------------------'
echo ''
sleep 1
magma 'arb_splitG2_random.mag'
echo ''
echo '------------------------------------------'
echo '  Finished Testing Over Arbitrary Fields  '
echo '------------------------------------------'
echo ''
echo ''
sleep 3
echo '--------------------------------------------------'
echo '  White Box Testing Over Characteristic 2 Fields  '
echo '--------------------------------------------------'
echo ''
sleep 1
magma 'ch2_splitG2_whiteBox_tester.mag'
echo ''
echo '-----------------------------------------------'
echo '  Random Testing Over Characterisitc 2 Fields  '
echo '-----------------------------------------------'
echo ''
sleep 1
magma 'ch2_splitG2_random.mag'
echo ''
echo '-------------------------------------------------'
echo '  Finished Testing Over Characteristic 2 Fields  '
echo '-------------------------------------------------'
echo ''
echo ''
sleep 3
echo '----------------------------------------------------'
echo '  White Box Testing Over Characteristic !=2 Fields  '
echo '----------------------------------------------------'
echo ''
sleep 1
magma 'nch2_splitG2_whiteBox_tester.mag'
echo ''
echo '-------------------------------------------------'
echo '  Random Testing Over Characteristic !=2 Fields  '
echo '-------------------------------------------------'
echo ''
sleep 1
magma 'nch2_splitG2_random.mag'
echo ''
echo '---------------------------------------------------'
echo '  Finished Testing Over Characteristic !=2 Fields  '
echo '---------------------------------------------------'
echo ''
echo ''
sleep 3
cd ../../ramifiedModel
echo '------------------------------------------------------------------------'
echo '-         TESTING EXPLICIT GENUS 2 RAMIFIED MODEL ARITHMETIC           -'
echo '------------------------------------------------------------------------'
echo ''
echo ''
sleep 5
echo '-------------------------------------------'
echo '  White Box Testing Over Arbitrary Fields  '
echo '-------------------------------------------'
echo ''
sleep 1
magma 'arb_ramifiedG2_whiteBox_tester.mag'
echo ''
echo '----------------------------------------'
echo '  Random Testing Over Arbitrary Fields  '
echo '----------------------------------------'
echo ''
sleep 1
magma 'arb_ramifiedG2_random.mag'
echo ''
echo '------------------------------------------'
echo '  Finished Testing Over Arbitrary Fields  '
echo '------------------------------------------'
echo ''
echo ''
sleep 3
echo '--------------------------------------------------'
echo '  White Box Testing Over Characteristic 2 Fields  '
echo '--------------------------------------------------'
echo ''
sleep 1
magma 'ch2_ramifiedG2_whiteBox_tester.mag'
echo ''
echo '-----------------------------------------------'
echo '  Random Testing Over Characteristic 2 Fields  '
echo '-----------------------------------------------'
echo ''
sleep 1
magma 'ch2_ramifiedG2_random.mag'
echo ''
echo '-------------------------------------------------'
echo '  Finished Testing Over Characteristic 2 Fields  '
echo '-------------------------------------------------'
echo ''
echo ''
sleep 3
echo '----------------------------------------------------'
echo '  White Box Testing Over Characteristic !=2 Fields  '
echo '----------------------------------------------------'
echo ''
sleep 1
magma 'nch2_ramifiedG2_whiteBox_tester.mag'
echo ''
echo '-------------------------------------------------'
echo '  Random Testing Over Characteristic !=2 Fields  '
echo '-------------------------------------------------'
echo ''
sleep 1
magma 'nch2_ramifiedG2_random.mag'
echo ''
echo '---------------------------------------------------'
echo '  Finished Testing Over Characteristic !=2 Fields  '
echo '---------------------------------------------------'
echo ''
echo ''
sleep 3
cd ../../g3
echo ''
echo ''
echo ''
echo '---------------------------------------'
echo '- TESTING EXPLICIT GENUS 3 ARITHMETIC -'
echo '---------------------------------------'
echo ''
cd splitModel
echo ''
echo ''
echo ''
echo '-------------------------------------------------------------------------------'
echo '- TESTING EXPLICIT GENUS 3 BALANCED SPLIT MODEL ARITHMETIC (Negative Reduced) -'
echo '-------------------------------------------------------------------------------'
echo ''
echo ''
sleep 5
cd negReduced
echo '-------------------------------------------'
echo '  White Box Testing Over Arbitrary Fields  '
echo '-------------------------------------------'
echo ''
sleep 1
magma 'arb_splitG3_whitebox_tester.mag'
echo ''
echo '----------------------------------------'
echo '  Random Testing Over Arbitrary Fields  '
echo '----------------------------------------'
echo ''
sleep 1
magma 'arb_splitG3_random.mag'
echo ''
echo '------------------------------------------'
echo '  Finished Testing Over Arbitrary Fields  '
echo '------------------------------------------'
echo ''
echo ''
sleep 3
#echo '--------------------------------------------------'
#echo '  White Box Testing Over Characteristic 2 Fields  '
#echo '--------------------------------------------------'
#echo ''
#sleep 1
#magma 'ch2_splitG3_whiteBox_tester.mag'
echo ''
echo '-----------------------------------------------'
echo '  Random Testing Over Characterisitc 2 Fields  '
echo '-----------------------------------------------'
echo ''
sleep 1
magma 'ch2_splitG3_random.mag'
echo ''
echo '-------------------------------------------------'
echo '  Finished Testing Over Characteristic 2 Fields  '
echo '-------------------------------------------------'
echo ''
echo ''
sleep 3
echo '----------------------------------------------------'
echo '  White Box Testing Over Characteristic !=2 Fields  '
echo '----------------------------------------------------'
echo ''
sleep 1
magma 'nch2_splitG3_whitebox_tester.mag'
echo ''
echo '-------------------------------------------------'
echo '  Random Testing Over Characteristic !=2 Fields  '
echo '-------------------------------------------------'
echo ''
sleep 1
magma 'nch2_splitG3_random.mag'
echo ''
echo '---------------------------------------------------'
echo '  Finished Testing Over Characteristic !=2 Fields  '
echo '---------------------------------------------------'
echo ''
echo ''
sleep 3
if (( $SECONDS > 60 )) ; then
    let "minutes=(SECONDS%3600)/60"
    let "seconds=(SECONDS%3600)%60"
    echo "All testing completed in $minutes minute(s) and $seconds second(s)"
else
    echo "All testing completed in $SECONDS seconds"
fi
echo ''
echo ''