"""Generate a Magma whitebox tester from a case generator in genFiles/.

A generator is a Magma script that loops over random curves and divisor pairs,
prints a `@B` .. `@E` block for each operation whose result agrees with Magma's own
Cantor arithmetic, and lets the formula's own ADD_DEBUG/DBL_DEBUG label name the
branch. Collecting one block per distinct label yields a tester holding a frozen
case for every branch. Coverage is therefore a random search, not a construction --
what makes the result valuable is that it is complete and replayable, not that any
case was hand-built.

Rewritten from a version that could not run here, and in fact could not run
anywhere as committed:

  * it drove the generator as `Popen(["magma", ...])`, needing Magma on PATH, then
    SIGSTOPped that pid every ten seconds to scrape the log and SIGCONTed it. Magma
    runs in a container in this repository, where signalling the wrapper does not
    pause Magma inside it;
  * `f.truncate(0)` reset the log while Magma still held it open at its own write
    offset, so the next block landed after a hole. The committed
    logs/{arb,nch2}_splitG3_log.txt both begin mid-polynomial, which is that race;
  * the generators looped `while true`, terminating only by being killed;
  * it was hardcoded to one family, `FileInfo("nch2","split","2")`;
  * and its module-level driver was hardcoded to one family, so `--from-log` and a
    choice of budget did not exist.

Now the generator carries its own trial bound (WB_TRIALS) and writes where it is
told (WB_LOG), so this runs it once, waits, and parses the finished log. Anything
the trials failed to reach is reported rather than looped on forever.

Usage:
    ./whitebox_auto_NEG.py ch2 split 3 --trials 400 --out ../g3/.../x.mag
    ./whitebox_auto_NEG.py ch2 split 3 --from-log logs/ch2_splitG3_log.txt
"""

import argparse
import os
import subprocess
import sys

#fieldType = arb, ch2, nch2
#curveType = ramified, split
#genus     = integer greater than 1
#tagDigit  = (DBL_DEBUG digits, ADD_DEBUG digits)
class FileInfo(object):
    def __init__(self, fieldType, curveType, genus, basis="neg"):
        # Only the split model has a reduced-basis subdirectory. This was
        # unconditional, so every ramified path pointed at a
        # ../g2/ramifiedModel/negReduced/ that has never existed -- which is most of
        # why only one family was ever reachable.
        #
        # The basis was then hardcoded to negReduced, which meant the three
        # posReduced genus-2 split testers could not be regenerated by this tool at
        # all. They are not interchangeable: a case records the result the formulas
        # produced, and the two bases normalise v against different polynomials at
        # infinity, so a negReduced case replayed against posReduced formulas
        # compares a different divisor. `whitebox.py` already keys on the basis for
        # exactly that reason. Genus 3 ships negReduced only, so `basis` is only
        # ever exercised at genus 2 -- but hardcoding it made three of the fifteen
        # testers unmaintainable, which is why it is a parameter now.
        self.BASIS = basis
        if curveType == "split":
            sub = "posReduced/" if basis == "pos" else "negReduced/"
            self.PATH = "../g" + genus + "/" + curveType + "Model/" + sub
        else:
            self.PATH = "../g" + genus + "/" + curveType + "Model/"
        self.GEN = "genFiles/" + fieldType + "_" + curveType + "G" + genus + "_WB_gen.mag"
        self.ADD = "g" + genus + "Formulas/" + fieldType + "_" + curveType + "G" + genus + "_ADD.mag"
        self.DBL = "g" + genus + "Formulas/" + fieldType + "_" + curveType + "G" + genus + "_DBL.mag"
        self.UTL = "g" + genus + "Formulas/" + fieldType + "_" + curveType + "G" + genus + "_UTL.mag"
        self.LOG = "logs/" + fieldType + "_" + curveType + "G" + genus + "_log.txt"
        self.OUT = "testerFiles/" + fieldType + "_" + curveType + "G" + str(genus) + "_whiteBox_tester.mag"
        self.GENUS = genus
        self.FIELD = fieldType;

        if curveType == "split":
            self.split = True
        else:
            self.split = False

        # The shared polynomial-arithmetic file the tester must load. Genus 2 split
        # keeps it in reduced_basis_arithmetic.mag; genus 3 split renamed it to
        # poly_balanced_arithmetic.mag, which is what the deployed genus-3 testers
        # load and what the emitter below had hardcoded wrongly.
        if self.split:
            if genus == "2":
                self.ARITH = "reduced_basis_arithmetic.mag"
            else:
                self.ARITH = "poly_balanced_arithmetic.mag"
        else:
            self.ARITH = "ramifiedUtilities.mag"

        self.dblNum = 0
        #Counts DBL cases
        f = open(self.PATH + self.DBL, "r")        
        raw = f.readlines()

        for line in raw:
            if "DBL_DEBUG" in line:
                self.dblNum = self.dblNum + 1
        f.close()
        self.dblTag = "{0:0=" + str(len(str(self.dblNum))) + "d}"


        self.addNum = 0
        #Counts ADD cases
        f = open(self.PATH + self.ADD, "r")        
        raw = f.readlines()

        for line in raw:
            if "ADD_DEBUG" in line:
                self.addNum = self.addNum + 1
        f.close()
        self.addTag = "{0:0=" + str(len(str(self.addNum))) + "d}"    



def _evenChar(field):
    """Is this field size a power of two, i.e. characteristic 2?

    Field sizes here are prime powers -- 2,3,4,5,7,8,9,11,13,16,25,27,32 -- so a
    power of two is exactly characteristic 2 and nothing else is. Used to keep the
    two-case quota per characteristic class rather than per family, which is what
    lets `arb` hold two odd-characteristic cases and two even ones.
    """
    q = int(str(field).strip())
    return q > 0 and (q & (q - 1)) == 0


class CaseGen(object):
    """Runs a generator once, then parses its log into cases per branch."""

    def __init__(self, fileInfo, magmaCmd=None, trials=400, seed=1, pairs=4000,
                 extra=None, perChar=2):
        self.file = fileInfo
        self.magmaCmd = magmaCmd or ["../tools/magma-docker/magma.sh"]
        self.trials = trials
        self.seed = seed
        self.pairs = pairs
        self.extra = extra or {}
        # Cases to keep per branch per characteristic class, each from a different
        # field. See `_takeCase` for why this is two and why they must differ.
        self.perChar = perChar

    def expectedTags(self):
        """The branch labels a complete tester must hold.

        Derived the way the original did -- from the count of DEBUG lines in each
        formula file, zero-padded -- because that is what the generators' labels
        were numbered against.
        """
        dbl = ["DBL" + self.file.dblTag.format(i) for i in range(self.file.dblNum)]
        add = ["ADD" + self.file.addTag.format(i) for i in range(self.file.addNum)]
        return dbl, add

    def runGenerator(self, logPath):
        """Run the generator to completion, writing its log to logPath."""
        env = dict(os.environ)
        env["WB_TRIALS"] = str(self.trials)
        env["WB_SEED"] = str(self.seed)
        env["WB_PAIRS"] = str(self.pairs)
        for name, val in self.extra.items():
            env[name] = str(val)
        env["WB_LOG"] = logPath
        env["WB_BASIS"] = self.file.BASIS
        # magma.sh forwards only what MAGMA_ENV names, so a variable missing here
        # silently does not reach the generator -- which is how a printed replay
        # seed once turned out to be an instruction that did not work.
        env["MAGMA_ENV"] = ("WB_TRIALS WB_SEED WB_LOG WB_PAIRS WB_BASIS "
                            "WB_SWEEP WB_TDEG WB_CELL WB_FIELDS WB_WITNESS")

        if os.path.exists(logPath):
            os.remove(logPath)

        print("running %s: %d curves, %s pairs/curve, seed %d"
              % (self.file.GEN, self.trials,
                 "exhaustive" if self.pairs == 0 else self.pairs, self.seed))
        proc = subprocess.run(self.magmaCmd + [self.file.GEN], env=env,
                              stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
        out = proc.stdout.decode("utf-8", "replace")
        if proc.returncode != 0:
            sys.stderr.write(out)
            raise SystemExit("magma exited %d" % proc.returncode)
        # Magma exits 0 on a failed assertion, so the output must be read.
        for marker in ("Runtime error", "User error", "Assertion failed"):
            if marker in out:
                sys.stderr.write(out)
                raise SystemExit("magma reported %r" % marker)
        if not os.path.exists(logPath):
            sys.stderr.write(out)
            raise SystemExit("generator produced no log at %s" % logPath)

    def parseLog(self, logPath):
        """Collect the first block for each branch label.

        A `failed` line means the formula disagreed with Cantor. The generator
        prints it instead of a block and carries on; here it is fatal, because a
        tester must not be built from a run that contained a wrong answer.
        """
        dblCases, addCases = self.expectedTags()
        wanted = set(dblCases) | set(addCases)
        cases, failures, blocks = {}, 0, 0

        with open(logPath, "r") as f:
            raw = f.readlines()

        processing, current = False, []
        for line in raw:
            if "failed" in line:
                failures += 1
            if "@B" in line:
                processing, current = True, []
            elif processing and "@E" in line:
                processing = False
                blocks += 1
                self._takeCase(cases, current, wanted)
                current = []
            elif processing:
                current.append(line.strip())

        if failures:
            raise SystemExit("generator reported %d failed comparison(s) in %s; "
                             "refusing to build a tester from it"
                             % (failures, logPath))

        self.applyQuota(cases)
        missing = sorted(t for t in (set(dblCases) | set(addCases)) if t not in cases)
        nCases = sum(len(v) for v in cases.values())
        print("%d blocks parsed, %d of %d branches covered, %d case(s) kept"
              % (blocks, len(cases), len(dblCases) + len(addCases), nCases))
        if missing:
            print("%d branch(es) not reached by this search:" % len(missing))
            print("  " + " ".join(missing))

        # A branch that reached its quota is as detectable as this ladder can make
        # it; one that did not is a branch where a change may still be invisible,
        # which is the whole of ERRATA E20. So the shortfall is REPORTED. A silent
        # one-case branch is exactly what let a correct saving be reverted.
        fields = sorted({c[0].strip() for v in cases.values() for c in v},
                        key=lambda x: int(x))
        classes = sorted({_evenChar(f) for f in fields})
        want = self.perChar * len(classes)
        short = {t: len(v) for t, v in cases.items() if len(v) < want}
        print("  fields present: %s; quota %d per branch (%d per characteristic "
              "class x %d class(es) available)"
              % (", ".join("GF(%s)" % f for f in fields), want, self.perChar,
                 len(classes)))
        if short:
            byCount = {}
            for t, n in sorted(short.items()):
                byCount.setdefault(n, []).append(t)
            print("  %d branch(es) below quota -- extend the ladder to fix:"
                  % len(short))
            for n in sorted(byCount):
                print("    %d case(s): %s" % (n, " ".join(byCount[n])))
        else:
            print("  every branch reached the quota")
        return cases, missing

    def applyQuota(self, cases):
        """Keep `perChar` cases per label per characteristic class, in LADDER order.

        `_takeCase` banks one block per (label, field); this decides which survive.
        Two per class rather than one because even a good single case leaves about
        10% of a family's assignments invisible, and a second at a DIFFERENT field
        takes it to about 7% -- while a second at the SAME field gives 11.8%, worse
        than one case at a bigger field, since same-field failures are correlated.
        That is why the fields must differ, and it is the robust part of this rule.

        LADDER ORDER, not largest-first, and this reverses an earlier version of
        this method. "A bigger field has fewer coincidences" is true on average and
        useless as a selection rule, because the variance between individual cases
        swamps it. Measured on nch2 genus 2, same generator, same 400 curves per
        field, only the ladder differing:

            ladder            kept    invisible of 236
            {3,5,7}           3,5,7          13
            {3,7,11}          3,7,11         13
            {3,5}             3,5            14
            {3,5,7,9,11}      9,11           24   <-- largest-first picked these
            one case, shipped 3,5,7           16

        Largest-first turned a corpus that should have improved on the shipped one
        into a REGRESSION, 16 invisible becoming 24. Taking the ladder in order
        makes the ladder the knob -- visible in the generator, chosen per family by
        measurement -- rather than burying the choice in a heuristic that cannot be
        seen from the outside. A family whose best pair is its two largest fields
        simply lists those two.

        Nothing is discarded silently: `parseLog` prints the fields kept and names
        every branch left below quota, which is what the ladder is extended to fix.
        """
        for tag, held in cases.items():
            keep = []
            for even in (False, True):
                same = [c for c in held if _evenChar(c[0]) == even]
                keep.extend(same[:self.perChar])
            cases[tag] = keep

    def _takeCase(self, cases, current, wanted):
        """Store a block under the label the formula printed.

        The label is the first line of the block because ADD_DEBUG/DBL_DEBUG print
        it from inside the formula. It is compared stripped: ADD082 carries a
        trailing space in all three genus-3 split ADD files.

        TWO CASES PER LABEL PER CHARACTERISTIC, FROM DIFFERENT FIELDS.

        This used to keep the FIRST block per label and refuse the rest. Since the
        generators loop `for F in FIELDS` with FIELDS ascending, that made every
        branch's one case come from the SMALLEST field reaching it -- the most
        degenerate arithmetic available -- which is the second cause of ERRATA E20:
        `ADD33`'s case had `t8 = 0`, so the corpus could not distinguish a change to
        that term, and a correct saving was reverted because breaking the line
        deliberately also measured green.

        Measured, on the genus-3 nch2 family, mutating every executed assignment
        and asking whether the returned divisor moves:

            one case at GF(3), as shipped      20.0% of assignments invisible
            one case at GF(5)                   9.7%
            TWO cases both at GF(3)            11.8%   <-- worse than one at GF(5)
            two cases, GF(3) and GF(5)          7.1%

        So one case per (label, field) is a CONSTRAINT and not a preference: two
        draws at the same field share that field's coincidence probabilities, and
        the second is blind to most of what the first is. Spreading across fields
        is what buys the detectability.

        The quota is per characteristic class, which is what gives `arb` four cases
        without a per-family table: `nch2` admits only odd fields and `ch2` only
        even ones, so each takes two, while `arb` admits both and takes two of
        each. That matters for `arb` specifically -- as shipped its genus-3 corpus
        is 45 cases in characteristic 2 against 3 in odd characteristic, so 45 of
        its 48 branches have never been whiteboxed in odd characteristic at all, in
        the one family that must work in every characteristic.
        """
        if not current or len(current) < 2:
            return
        tag = current[0].strip()
        if tag not in wanted:
            return
        field = current[1].strip()
        held = cases.get(tag, ())
        # One per (label, field). The quota itself is NOT applied here: blocks
        # arrive in whatever order the generator emitted them, and for the
        # genus-3 families that order is ascending by field, so applying the
        # quota greedily would keep the two SMALLEST fields -- a milder version
        # of the bias this whole change exists to remove. Measured on ch2 genus
        # 3, whose log holds GF(2), GF(4) and GF(8): keeping the first two gives
        # 88.2% detectability where keeping the largest two gives more. So every
        # field is banked here and `applyQuota` prunes afterwards.
        if any(c[0].strip() == field for c in held):
            return

        def divisor(s):
            return s.replace(' ', '').replace('<', '').replace('>', '').split(',')

        if self.file.split:
            # label, F, f, h, Vp, Vn, RD1, RD2, result
            if len(current) < 9:
                return
            curve = [current[2], current[3], current[4], current[5]]
            divs = [divisor(current[6]), divisor(current[7])]
            result = current[8]
        else:
            # label, F, f, h, RD1, RD2, result
            if len(current) < 7:
                return
            curve = [current[2], current[3]]
            divs = [divisor(current[4]), divisor(current[5])]
            result = current[6]

        if tag.startswith("DBL"):
            divs = divs[:1]
        cases.setdefault(tag, []).append((current[1], curve, divs, result))


class Magma(object):
    def __init__(self, fileInfo, cases):
        self.file = fileInfo
        self.magma = []
        self.cases = cases
        self.generateCode()
        self.makeFile()
        

    def generateCase(self, case):
        g = int(self.file.GENUS)

        self.magma.append('FF := GF(' + case[1][0] + ');\n')
        self.magma.append('R<x>:=PolynomialRing(FF);\n')
        self.magma.append('f:= R! ' + case[1][1][0] + ';\n')
        self.magma.append('h:= R! ' + case[1][1][1] + ';\n')

        if self.file.split:
            self.magma.append('V:= R! ' + case[1][1][2] + ';\n')
            self.magma.append('Vn:= -V - h;\n')
            self.magma.append('ccs:= Precompute(f,h,' + case[1][0] + ');\n')
            self.magma.append('\n')

            
            # Return list and the polynomials rebuilt from it. Every term carries
            # an explicit *x^i, including x^1 and x^0, matching the deployed
            # genus-3 testers so a regenerated file can be diffed against them.
            returned = 'un' + str(g)
            polyU = 'un' + str(g) + '*x^' + str(g)
            # The formulas return v only up to degree g-1; its top two
            # coefficients come from the BASIS polynomial, which differs by basis.
            # Hardcoding Vn here would have made a posReduced tester rebuild v
            # against the negative basis and compare a different divisor.
            _bp = "V" if self.file.BASIS == "pos" else "Vn"
            polyV = ('Coeff(' + _bp + ',' + str(g+1) + ')*x^' + str(g+1)
                     + ' + Coeff(' + _bp + ',' + str(g) + ')*x^' + str(g))

            i = g - 1
            while i >= 0:
                returned = returned + ',un' + str(i)
                polyU = polyU + ' + un' + str(i) + '*x^' + str(i)
                i = i - 1

            i = g - 1
            while i >= 0:
                returned = returned + ',vn' + str(i)
                polyV = polyV + ' + vn' + str(i) + '*x^' + str(i)
                i = i - 1

            # A split divisor is the 3-tuple <u, v, n>. The emitter used to write a
            # 4-tuple <u, v, ExactQuotient(f - v*(v+h),u), n> and read n from
            # index 3 of the parsed divisor, which is a stale generation: the
            # generators print NegativeReducedBasis, which returns <D[1],vhat,D[3]>,
            # and every deployed genus-3 tester writes <U1, V1, N1>. Reading index 3
            # of a 3-element list is an IndexError, so this path could not have
            # produced the deployed testers.
            #
            # AdaptedBasis inverts NegativeReducedBasis, recovering the divisor the
            # generator actually handed to Cantor. Comparing in the reduced basis is
            # what the deployed testers do, and it is also the only comparison the
            # formulas' output supports: they return v only up to degree g-1, with
            # the top two coefficients taken from Vn.
            # The WEIGHT IS THE LAST ELEMENT of the emitted divisor, not index 2.
            # The two genuses talk to different reference libraries and those
            # libraries disagree on the divisor's shape: genus 2 loads
            # reduced_basis_arithmetic.mag, whose divisor is <u, v, w, n> with
            # w = (f - v(v+h))/u carried explicitly, and genus 3 loads
            # poly_balanced_arithmetic.mag, whose divisor is <u, v, n> --
            # `AdaptedBasis` there returns <D[1], vhat, D[3]>, three slots.
            #
            # Reading index 2 is right at genus 3 and picks up the COFACTOR at
            # genus 2, so `N2 := x + FF.1^2` -- a polynomial where an integer
            # weight belongs, and the case is then unparseable. This is the exact
            # inverse of the defect PR12 fixed: it changed the emitter from the
            # 4-tuple form to the 3-tuple one for genus 3 and thereby broke genus
            # 2, which went unnoticed because no genus-2 split tester has been
            # regenerated since. `d[-1]` is correct under both conventions.
            def _divisor(d, k):
                self.magma.append('U' + k + ' := R! ' + d[0] + ';\n')
                self.magma.append('V' + k + ' := R! ' + d[1] + ';\n')
                self.magma.append('N' + k + ' := ' + d[-1] + ';\n')

            # w is redundant rather than extra -- derivable from (u, v, f, h) --
            # so genus 2 reconstructs it inline exactly as its deployed testers
            # do, instead of carrying the generator's copy through the log.
            def _tuple(k):
                if g == 2:
                    return ('<U%s, V%s, ExactQuotient(f - V%s*(V%s + h),U%s), N%s>'
                            % (k, k, k, k, k, k))
                return '<U%s, V%s, N%s>' % (k, k, k)

            # Genus 2 hands its divisors straight to the generic library, so it
            # needs no basis conversion; genus 3 converts with AdaptedBasis. And
            # the library's own operation is basis-specific at genus 2, where both
            # bases ship -- Add_SPLIT_POS against Add_SPLIT_NEG -- so a posReduced
            # tester asserting against the NEG operation would compare the wrong
            # divisor and fail for the right reason.
            suffix = "POS" if self.file.BASIS == "pos" else "NEG"
            basisPoly = "V" if self.file.BASIS == "pos" else "Vn"

            if 'DBL' in case[0]:
                _divisor(case[1][2][0], '1')
                self.magma.append('D1 := ' + _tuple('1') + ';\n')
                if g == 2:
                    self.magma.append(returned + ',nN := DBL(U1,V1,N1,ccs);\n')
                    self.magma.append('nU:= R! ' + polyU + ';\n')
                    self.magma.append('nV:= R! ' + polyV + ';\n')
                    self.magma.append('Cantor:= Double_SPLIT_%s(D1,f,h,%s,2);\n'
                                      % (suffix, basisPoly))
                    self.magma.append('assert <nU,nV,ExactQuotient(f - nV*(nV + '
                                      'h),nU), nN> eq Cantor;\n\n')
                else:
                    self.magma.append('AD1 := AdaptedBasis(D1,f,h);\n')
                    self.magma.append(returned + ',nN := DBL(U1,V1,N1,ccs);\n')
                    self.magma.append('nU:= R! ' + polyU + ';\n')
                    self.magma.append('nV:= R! ' + polyV + ';\n')
                    self.magma.append('Cantor:= NegativeReducedBasis(Double(AD1,f,h,V),f,h);\n')
                    self.magma.append('assert <nU,nV,nN> eq Cantor;\n\n')

            else:
                _divisor(case[1][2][0], '1')
                _divisor(case[1][2][1], '2')
                self.magma.append('D1 := ' + _tuple('1') + ';\n')
                self.magma.append('D2 := ' + _tuple('2') + ';\n')
                if g == 2:
                    self.magma.append(returned + ', nN := ADD(U1,V1,N1,U2,V2,N2,ccs);\n')
                    self.magma.append('nU:= R! ' + polyU + ';\n')
                    self.magma.append('nV:= R! ' + polyV + ';\n')
                    self.magma.append('Cantor:= Add_SPLIT_%s(D1,D2,f,h,%s,2);\n'
                                      % (suffix, basisPoly))
                    self.magma.append('assert <nU,nV,ExactQuotient(f - nV*(nV + '
                                      'h),nU), nN> eq Cantor;\n\n')
                else:
                    self.magma.append('AD1 := AdaptedBasis(D1,f,h);\n')
                    self.magma.append('AD2 := AdaptedBasis(D2,f,h);\n')
                    self.magma.append(returned + ', nN := ADD(U1,V1,N1,U2,V2,N2,ccs);\n')
                    self.magma.append('nU:= R! ' + polyU + ';\n')
                    self.magma.append('nV:= R! ' + polyV + ';\n')
                    self.magma.append('Cantor:= NegativeReducedBasis(Add(AD1,AD2,f,h,V),f,h);\n')
                    self.magma.append('assert <nU,nV,nN> eq Cantor;\n\n')

        else:
            self.magma.append('C:= HyperellipticCurve(f,h);\n')
            self.magma.append('J:= Jacobian(C);\n')
            self.magma.append('\n')
            
            returned = 'un' + str(g)
            polyU = 'un' + str(g) +'*x^' +str(g)

            i = g - 1
            while i >= 0:
                returned = returned + ',un' + str(i)
                polyU = polyU + ' + un' + str(i) +'*x^' + str(i)
                i = i-1
            
            i = g - 1
            polyV = 'vn' + str(i) +'*x^' + str(i)
            returned = returned + ',vn' + str(i)

            i = i-1
            while i >= 0:
                returned = returned + ',vn' + str(i)
                polyV = polyV + ' + vn' + str(i) +'*x^' + str(i)
                i = i-1




            if 'DBL' in case[0]:
                self.magma.append('U1 := R!' + case[1][2][0][0] + ';\n')
                self.magma.append('V1 := R!' + case[1][2][0][1] + ';\n')
                self.magma.append('D1 := J![U1,V1];\n')

                if self.file.FIELD == "nch2":
                    self.magma.append(returned + ' := DBL(U1,V1,f);\n')
                else:
                    self.magma.append(returned + ' := DBL(U1,V1,f,h);\n')

                self.magma.append('nU:= R! ' + polyU + ';\n')
                self.magma.append('nV:= R! ' + polyV + ';\n')
                self.magma.append('Cantor:= 2*D1;\n')
                self.magma.append('assert (' + polyU + ') eq Cantor[1] and (' + polyV + ') eq Cantor[2];\n')
                self.magma.append('\n\n')
                

            else:
                self.magma.append('U1 := R!' + case[1][2][0][0] + ';\n')
                self.magma.append('V1 := R!' + case[1][2][0][1] + ';\n')
                self.magma.append('U2 := R!' + case[1][2][1][0] + ';\n')
                self.magma.append('V2 := R!' + case[1][2][1][1] + ';\n')
                self.magma.append('D1 := J![U1,V1];\n')
                self.magma.append('D2 := J![U2,V2];\n')

                if self.file.FIELD == "nch2":
                    self.magma.append(returned + ' := ADD(U1,V1,U2,V2,f);\n')
                else:
                    self.magma.append(returned + ' := ADD(U1,V1,U2,V2,f,h);\n')
                
                self.magma.append('nU:= R! ' + polyU + ';\n')
                self.magma.append('nV:= R! ' + polyV + ';\n')
                self.magma.append('Cantor:= D1 + D2;\n')
                self.magma.append('assert (' + polyU + ') eq Cantor[1] and (' + polyV + ') eq Cantor[2];\n')
                self.magma.append('\n\n')


    def generateCode(self):
        self.magma.append('ADD_DEBUG := true;\n')
        self.magma.append('DBL_DEBUG := true;\n')

        if self.file.split:
            self.magma.append('UTL_DEBUG := false;\n')
            self.magma.append('load "' + self.file.ARITH + '";\n')
            self.magma.append('load "' + self.file.UTL + '";\n')
        else:
            self.magma.append('load "' + self.file.ARITH + '";\n')

        self.magma.append('load "' + self.file.DBL + '";\n')
        self.magma.append('load "' + self.file.ADD + '";\n')
        self.magma.append('"";' + '\n\n')

        # Sorted by branch label rather than by the order the search happened to
        # find them, so two runs that cover the same branches produce the same file
        # and a regenerated tester can be diffed against its predecessor.
        # A label now holds a LIST of cases -- two per characteristic class, each
        # from a different field. Emitted in field order within the label so the
        # file is a function of (seed, budget) and two runs covering the same
        # branches still diff cleanly.
        totalCases = 0
        for tag, held in sorted(self.cases.items()):
            for one in sorted(held, key=lambda c: int(c[0].strip())):
                totalCases = totalCases + 1
                self.generateCase((tag, one))

        self.magma.append('"\nTotal Cases: ' + str(totalCases) +'";\n')
        self.magma.append("quit;")
        



    def makeFile(self):
        with open(self.file.OUT, 'w+') as out:
            out.writelines(self.magma)


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("field", choices=["arb", "nch2", "ch2"])
    ap.add_argument("curve", choices=["split", "ramified"])
    ap.add_argument("genus")
    ap.add_argument("--trials", type=int, default=400,
                    help="random curves to try (default 400)")
    ap.add_argument("--seed", type=int, default=1,
                    help="Magma seed, so the search is reproducible (default 1)")
    ap.add_argument("--sweep", type=int, default=None,
                    help="curves per deg(W0) class per field in the deliberate "
                         "phase; 0 skips it")
    ap.add_argument("--tdeg", type=int, default=None,
                    help="max deg(u) of class targets for the class-targeted "
                         "pair mode (0 = the u=1 classes)")
    ap.add_argument("--cell", type=int, default=None,
                    help="pairs per shape-matrix cell")
    ap.add_argument("--witness", type=int, default=None,
                    help="run the witness-curve phase (curves kept because a "
                         "Precompute leaf they reach is too rare to sample)")
    ap.add_argument("--fields", default=None,
                    help="comma separated field sizes, overriding the generator's")
    ap.add_argument("--pairs", type=int, default=4000,
                    help="cap on ADD pairs per curve; 0 means exhaustive over the "
                         "curve's whole divisor space (default 4000)")
    ap.add_argument("--out", help="where to write the tester (default testerFiles/)")
    ap.add_argument("--log", help="where the generator writes its log "
                                  "(default a scratch file beside logs/)")
    ap.add_argument("--from-log", dest="fromLog",
                    help="parse an existing log instead of running Magma")
    ap.add_argument("--magma", default="../tools/magma-docker/magma.sh",
                    help="Magma command (default the container wrapper)")
    ap.add_argument("--basis", choices=["neg", "pos"], default="neg",
                    help="split model reduced basis (default neg). Genus 3 ships "
                         "negReduced only; at genus 2 both exist and their cases "
                         "are NOT interchangeable, so posReduced testers must be "
                         "generated against posReduced formulas")
    ap.add_argument("--per-char", dest="perChar", type=int, default=2,
                    help="cases to keep per branch per characteristic class, each "
                         "from a different field (default 2, so nch2 and ch2 hold "
                         "two and arb four)")
    ap.add_argument("--allow-incomplete", action="store_true",
                    help="write the tester even if some branch was never reached")
    args = ap.parse_args(argv)

    fileInfo = FileInfo(args.field, args.curve, args.genus, basis=args.basis)
    if args.out:
        fileInfo.OUT = args.out

    gen = CaseGen(fileInfo, magmaCmd=[args.magma], trials=args.trials,
                  seed=args.seed, pairs=args.pairs, perChar=args.perChar,
                  extra={k: v for k, v in
                         (('WB_SWEEP', args.sweep), ('WB_TDEG', args.tdeg),
                          ('WB_CELL', args.cell), ('WB_FIELDS', args.fields),
                          ('WB_WITNESS', args.witness))
                         if v is not None})

    if args.fromLog:
        logPath = args.fromLog
    else:
        # Not fileInfo.LOG by default: whitebox/logs/ holds committed residue of the
        # last orchestrator run, and regenerating should not overwrite it.
        logPath = args.log or (fileInfo.LOG + ".new")
        gen.runGenerator(logPath)

    cases, missing = gen.parseLog(logPath)
    if missing and not args.allow_incomplete:
        raise SystemExit("refusing to write an incomplete tester; raise --trials, "
                         "or pass --allow-incomplete to accept the gap")
    if not cases:
        raise SystemExit("no cases parsed from %s" % logPath)

    Magma(fileInfo, cases)
    # Cases, not labels: a label now holds two. Reporting len(cases) here said
    # "48 cases" for a tester holding 94, which is the same class of misleading
    # count this PR exists to remove.
    print("wrote %s: %d case(s) across %d branch(es)"
          % (fileInfo.OUT, sum(len(v) for v in cases.values()), len(cases)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
